import { defineType, defineField } from 'sanity';
import { EnabledToggle } from '../components/EnabledToggle';

export default defineType({
  name: 'program',
  title: 'Program',
  type: 'document',
  groups: [
    { name: 'general', title: 'General', default: true },
    { name: 'landing', title: '📄 Landing Page' },
    { name: 'details', title: '📋 Details' },
    { name: 'seo', title: '🔍 SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'general',
    }),
    defineField({
      name: 'enabled',
      title: 'Show on Website',
      type: 'boolean',
      description: 'Toggle to control visibility on the live site.',
      initialValue: true,
      components: { input: EnabledToggle },
      group: 'general',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: 'Auto-generated from the title. This becomes the page URL (e.g. /programs/my-program/).',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
      group: 'general',
    }),
    defineField({
      name: 'template',
      title: 'Page Template',
      type: 'string',
      description: 'Choose the layout for this program page.',
      options: {
        list: [
          { title: 'Conference (flagship event)', value: 'conference' },
          { title: 'Book Studies (reading clubs)', value: 'book-studies' },
          { title: 'Masterclasses (short courses)', value: 'masterclasses' },
          { title: 'Seminar / Intensive (Faith & Reason)', value: 'seminar' },
          { title: 'Camp (residential youth)', value: 'camp' },
          { title: 'Standard (general-purpose)', value: 'standard' },
        ],
      },
      initialValue: 'conference',
      group: 'general',
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline / Quote',
      type: 'text',
      rows: 2,
      group: 'general',
    }),
    defineField({
      name: 'description',
      title: 'Short Description',
      type: 'text',
      rows: 3,
      description: 'Used on the Programs overview page cards',
      group: 'general',
    }),
    defineField({
      name: 'body',
      title: 'Full Description',
      type: 'array',
      of: [
        { type: 'block' },
        { type: 'image', options: { hotspot: true } },
      ],
      group: 'general',
    }),
    defineField({
      name: 'headerImage',
      title: 'Hero Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Recommended: 1600×900px or larger, landscape. Shown at the top of the program page.',
      group: 'general',
    }),

    // === Landing Page Sections ===
    defineField({
      name: 'introLabel',
      title: 'Intro Section Label',
      type: 'string',
      description: 'Small gold text above the heading, e.g. "What Are Inklings Clubs?"',
      group: 'landing',
    }),
    defineField({
      name: 'introHeading',
      title: 'Intro Section Heading',
      type: 'string',
      description: 'e.g. "Read Great Books. Build Community."',
      group: 'landing',
    }),
    defineField({
      name: 'introText',
      title: 'Intro Text',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'The main paragraphs in the intro section.',
      group: 'landing',
    }),
    defineField({
      name: 'introDetails',
      title: 'Intro Quick Facts',
      type: 'array',
      description: 'Quick-fact cards shown alongside the intro text (e.g. "Three studies per year", "Always free").',
      group: 'landing',
      of: [
        {
          type: 'object',
          name: 'introDetail',
          fields: [
            { name: 'title', title: 'Title', type: 'string', validation: (Rule: any) => Rule.required() },
            { name: 'subtitle', title: 'Subtitle', type: 'string' },
          ],
          preview: {
            select: { title: 'title', subtitle: 'subtitle' },
          },
        },
      ],
    }),
    defineField({
      name: 'readingListLabel',
      title: 'Reading List Section Label',
      type: 'string',
      description: 'e.g. "2026 Reading List"',
      group: 'landing',
    }),
    defineField({
      name: 'readingListHeading',
      title: 'Reading List Section Heading',
      type: 'string',
      description: 'e.g. "This Year\'s Books"',
      group: 'landing',
    }),
    // === Details ===
    defineField({
      name: 'audience',
      title: 'Audience',
      type: 'string',
      description: 'e.g. "Ages 12–18", "Catholic leaders", "All welcome"',
      group: 'details',
    }),
    defineField({
      name: 'format',
      title: 'Format',
      type: 'string',
      description: 'e.g. "4-night residential camp", "3-day intensive", "Monthly online"',
      group: 'details',
    }),
    defineField({
      name: 'frequency',
      title: 'Frequency',
      type: 'string',
      description: 'e.g. "Annual — October", "Year-round", "Summer"',
      group: 'details',
    }),
    defineField({
      name: 'pricing',
      title: 'Pricing',
      type: 'text',
      rows: 2,
      description: 'e.g. "$350/child" or "$50 early bird / $75 regular". Include family discounts or bursary info if available.',
      group: 'details',
    }),
    defineField({
      name: 'registrationUrl',
      title: 'Registration URL',
      type: 'url',
      group: 'details',
    }),
    defineField({
      name: 'contactPerson',
      title: 'Contact Person',
      type: 'reference',
      to: [{ type: 'person' }],
      group: 'details',
    }),
    defineField({
      name: 'relatedEvents',
      title: 'Related Events',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'event' }] }],
      group: 'details',
    }),
    defineField({
      name: 'testimonials',
      title: 'Testimonials',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'quote', title: 'Quote', type: 'text' },
            { name: 'attribution', title: 'Attribution', type: 'string' },
          ],
        },
      ],
      group: 'details',
    }),
    defineField({
      name: 'label',
      title: 'Label',
      type: 'string',
      description: 'Short label shown above the title, e.g. "Intensive Formation", "Youth Program", "Short Course"',
      group: 'general',
    }),
    defineField({
      name: 'highlights',
      title: 'Highlights',
      type: 'array',
      group: 'landing',
      description: 'Feature cards shown in a grid — e.g. "What You\'ll Experience", "What\'s Included". Leave empty to hide this section.',
      of: [
        {
          type: 'object',
          name: 'highlight',
          fields: [
            { name: 'title', title: 'Title', type: 'string', validation: (Rule: any) => Rule.required() },
            { name: 'description', title: 'Description', type: 'text', rows: 3 },
          ],
          preview: {
            select: { title: 'title', subtitle: 'description' },
          },
        },
      ],
    }),
    defineField({
      name: 'schedule',
      title: 'Schedule / Timeline',
      type: 'array',
      group: 'landing',
      description: 'Schedule items like "Day 1: Arrival & Orientation". Leave empty to hide.',
      of: [
        {
          type: 'object',
          name: 'scheduleItem',
          fields: [
            { name: 'label', title: 'Label', type: 'string', description: 'e.g. "Day 1", "Week 1-2", "Morning"' },
            { name: 'content', title: 'Content', type: 'text', rows: 2 },
          ],
          preview: {
            select: { title: 'label', subtitle: 'content' },
          },
        },
      ],
    }),
    defineField({
      name: 'whoItsFor',
      title: 'Who It\'s For',
      type: 'array',
      group: 'landing',
      description: 'Bullet points for "Is This For You?" section. Leave empty to hide.',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'ctaStatus',
      group: 'details',
      title: 'CTA Button Status',
      type: 'string',
      description: 'Controls the main action button. "Active" links to registration, "Interest List" shows a signup form, "Closed" shows greyed-out button.',
      options: {
        list: [
          { title: 'Active — Registration Open', value: 'active' },
          { title: 'Interest List — Collect Signups', value: 'interest' },
          { title: 'Closed — Not Currently Available', value: 'closed' },
        ],
        layout: 'radio',
      },
      initialValue: 'interest',
    }),
    defineField({
      name: 'ctaLabel',
      title: 'CTA Button Label',
      type: 'string',
      description: 'Override default button text. Defaults: "Register Now" (active), "Join the Interest List" (interest), "Registration Closed" (closed).',
      group: 'details',
    }),
    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      description: 'e.g. "Mt Carmel Spirituality Centre, Alberta" or "Online"',
      group: 'details',
    }),
    defineField({
      name: 'dates',
      title: 'Dates',
      type: 'string',
      description: 'Human-readable date string, e.g. "October 2-3, 2026" or "Year-round"',
      group: 'details',
    }),
    defineField({
      name: 'order',
      title: 'Sort Order',
      type: 'number',
      group: 'general',
    }),
    defineField({
      name: 'seo',
      group: 'seo',
      title: 'SEO',
      type: 'object',
      fields: [
        { name: 'metaTitle', title: 'Meta Title', type: 'string', description: 'Custom page title for search engines. Keep under 60 characters. If blank, the program title is used.' },
        { name: 'metaDescription', title: 'Meta Description', type: 'text', rows: 2, description: 'The snippet shown in Google search results. Keep under 160 characters. If blank, the short description is used.' },
        { name: 'ogImage', title: 'OG Image', type: 'image', description: 'The image shown when this page is shared on social media (Facebook, Twitter, iMessage, etc.). Recommended: 1200×630px, landscape. If left blank, the hero image is used.' },
      ],
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'audience', media: 'headerImage' },
  },
});
