// Old Wix URL → New site path (301 redirects)
// Used by worker-wrapper.js at the edge before Astro handles the request.

export const EXACT_REDIRECTS = {
  '/latest': '/library/',
  '/mission': '/about/',
  '/our-story': '/about/',
  '/leadership': '/about/leadership/',
  '/what-we-do': '/programs/',
  '/courses': '/programs/',
  '/coming-events': '/events/',
  '/book-online': '/events/',
  '/join-us': '/support/',
  '/donate': '/support/',
  '/donate-1': '/support/',
  '/contact-8': '/contact/',
  '/general-6': '/contact/',
  '/journals-and-merchandise': '/magnalia/subscribe/',
  '/product-page-1': '/magnalia/subscribe/',
  '/privacy-policy': '/privacy/',
  '/2025-impact-report': '/about/impact/',
  '/summer-internship': '/careers/',
  '/summer-interns': '/careers/',
  '/pdf': '/library/',
  '/novena-for-archbishop-hero': '/library/',

  '/post/meet-the-interns': '/library/meet-the-interns/',
  '/post/animal-farm-book-studies': '/library/animal-farm-book-studies/',
  '/post/internship-orientation-retreat': '/library/internship-orientation-retreat/',
  '/post/cyeg-and-ggi-pilgrimage-lecture-and-bbq': '/library/cyeg-and-ggi-pilgrimage-lecture-and-bbq/',
  '/post/stewardship-and-freedom-lessons-from-personal-finances-101': '/library/stewardship-and-freedom-lessons-from-personal-finances-101/',
  '/post/fine-gathering-in-ottawa-and-national-prayer-breakfast': '/library/fine-gathering-ottawa/',
  '/post/master-your-money-serve-your-vocation-finance-101': '/library/personal-finances/',
  '/post/medicine-forgets-its-vocation-alberta-places-guardrails': '/library/medicine-forgets-vocation/',
  '/post/ggi-at-provincial-prayer-breakfast': '/library/ggi-at-provincial-prayer-breakfast/',
  '/post/annual-keith-cassidy-lecture-cardinal-newman-among-the-doctors': '/library/annual-keith-cassidy-lecture-cardinal-newman-among-the-doctors/',
  '/post/a-reflection-on-rekindling-the-heart-marriage-retreat': '/library/a-reflection-on-rekindling-the-heart-marriage-retreat/',
  '/post/rekindling-the-hearth-a-joyful-st-valentine-s-marriage-retreat': '/library/rekindling-the-hearth-a-joyful-st-valentine-s-marriage-retreat/',
  '/post/renewal-of-culture-podcast-with-brett-powell-and-dr-topping': '/library/renewal-of-culture-podcast-with-brett-powell-and-dr-topping/',
  '/post/take-her-word-for-it-our-mother-knows': '/library/take-her-word-for-it-our-mother-knows/',
  '/post/why-classical-education-now': '/library/why-classical-education-now/',
  '/post/dr-topping-delivers-a-lecture-in-ontario-at-the-fellowship-of-catholic-scholars': '/library/dr-topping-delivers-a-lecture-in-ontario-at-the-fellowship-of-catholic-scholars/',
  '/post/charlie-kirk-and-cultural-renewal-with-victor-carpay': '/library/charlie-kirk-and-cultural-renewal-with-victor-carpay/',
  '/post/leading-newman-scholars-discuss-the-impact-of-newman-as-newman-becomes-a-doctor-of-the-church': '/library/leading-newman-scholars-discuss-the-impact-of-newman-as-newman-becomes-a-doctor-of-the-church/',
  '/post/first-renewing-culture-conference-cardinal-collins-and-upcoming-journal': '/library/first-renewing-culture-conference-cardinal-collins-and-upcoming-journal/',
  '/post/st-gregory-s-inklings-book-studies': '/library/st-gregory-s-inklings-book-studies/',
  '/post/the-abolition-of-man-webinar': '/library/abolition-of-man-guide/',
  '/post/st-gregory-folk-music-camp': '/programs/',

  '/event-details/faith-and-reason-seminar': '/programs/faith-and-reason/',
  '/event-details/first-annual-renewing-culture-conference': '/events/',
  '/event-details/first-annual-renewing-culture-conference-2': '/events/',
  '/event-details/st-gregorys-music-and-leadership-camp-1': '/programs/',
  '/event-details/october-webinar': '/events/',
  '/event-details/st-gregorys-inkling-book-club': '/programs/book-studies/',
  '/event-details/why-classical-education-now-raising-children-who-can-think-discern-and-believe': '/library/',
};

export const PREFIX_REDIRECTS = [
  { prefix: '/post/', target: '/library/' },
  { prefix: '/event-details/', target: '/events/' },
  { prefix: '/profile/', target: '/' },
  { prefix: '/members/', target: '/' },
];
